### ISSUE TITLE
关于 PHP7 那个“非空合并”语法糖

### ISSUE THREAD

**Issue by zhangwebb** [XiaoLer/xiaoler.github.io#1]
[两行代码给 PHP7 添加一个“非空合并”语法糖](http://0x1.im/blog/php/add-a-operator-to-php7.html)
——我觉得这是个非常“甜”的语法糖，很喜欢！就是需要小修改下源码……

如果不改但还想享用的话，可以这么干：

```
$a = 'name';
$b = ['naem' => 'Jack', 'age' => 27];
echo $b[$a] ??0?: 'Name bad.';
```

即把 **`??0?:`** 视为一个整体，前面是需要判断的变量，后面为默认值，的确是啰嗦了点（多敲俩字符），起码移植性好些，可读性嘛……习惯就好 (￣▽￣)"

**Comment by sursir** [comment]
赞
